<?
    /** @var ZFE_View $this */

    $config = Zend_Registry::get('config');
?>

<? if ($config->debug->develToolbar && $this->develToolbar): ?>
<div id="DevelClearFix"></div>
<div id="DevelToolbar">
    <? if ($config->debug->configViewer): ?>
    <div id="DevelConfigViewer" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Конфигурация</h4>
                </div>
                <div class="modal-body">
                    <?= $this->configTreeViewer($config->toArray()); ?>
                </div>
            </div>
        </div>
    </div>
    <? endif; ?>

    <? if ($config->doctrine->profile): ?>
    <div id="DevelSqlProfiler" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">SQL–профайлер</h4>
                </div>
                <div class="modal-body table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Тип</th>
                                <th>Время, мс</th>
                                <th>Запрос</th>
                                <th>Параметры</th>
                            </tr>
                        </thead>
                        <tbody>
                            <? $sumTime = 0; ?>
                            <? $numEvents = 0; ?>
                            <? foreach (Doctrine_Manager::connection()->getListener() as $key => $event) : /** @var Doctrine_Event $event */ ?>
                                <? if (!in_array($event->getName(), ['fetch', 'prepare'])): ?>
                                    <? $sumTime += $time = $event->getElapsedSecs(); ?>
                                    <? if (++$numEvents <= $config->debug->limitShowQueries): ?>
                                        <?
                                            $params = $event->getParams();
                                            if (!empty($params)) {
                                                $params = '<pre><ol><li>' . implode('</li><li>', $params) . '</li></ol></pre>';
                                            } else {
                                                $params = '';
                                            }
                                        ?>
                                        <tr style="vertical-align: top;">
                                            <td><?= $event->getName() ?></td>
                                            <td><?= round($time * 1000, 2) ?></td>
                                            <td>
                                                <div id="DevelSqlListing_<?= $key ?>" class="collapse"><?= $this->formatSql($event->getQuery()) ?></div>
                                                <a data-toggle="collapse" href="#DevelSqlListing_<?= $key ?>" class="collapsed">
                                                    <span class="sqlHide">скрыть запрос</span>
                                                    <span class="sqlShow">показать запрос</span>
                                                </a>
                                                
                                                <? if ($config->doctrine->backtrace): ?>
                                                <ol id="DevelSqlBacktrace_<?= $key ?>" class="collapse backtrace"><?
                                                    foreach ($event->getBacktrace() as $point) {
                                                        if (isset($point['file'])) {
                                                            echo '<li>' . $point['file'] . '(' . $point['line'] . '): ';
                                                            if (isset($point['class'])) {
                                                                echo $point['class'] . $point['type'];
                                                            }
                                                            echo $point['function'] . '(';
                                                            if (isset($point['args'])) {
                                                                $args = [];
                                                                foreach ($point['args'] as $arg) {
                                                                    if (is_object($arg)) {
                                                                        $args[] = get_class($arg);
                                                                    } else {
                                                                        $args[] = var_export($arg);
                                                                    }
                                                                }
                                                                echo implode(', ', $args);
                                                            }
                                                            echo ')</li>';
                                                        }
                                                    } ?></ol>
                                                <a data-toggle="collapse" href="#DevelSqlBacktrace_<?= $key ?>" class="collapsed">
                                                    <span class="sqlHide">скрыть цепочку вызовов</span>
                                                    <span class="sqlShow">показать цепочку вызовов</span>
                                                </a>
                                                <? endif; ?>
                                            </td>
                                            <td><?= $params ?></td>
                                        </tr>
                                    <? endif; ?>
                                <? endif; ?>
                            <? endforeach; ?>

                            <? if ($numEvents > $config->debug->limitShowQueries): ?>
                                <tr>
                                    <td colspan="4" class="text-center empty">Последующие запросы (<?= $numEvents - $config->debug->limitShowQueries ?> шт) скрыты.</td>
                                </tr>
                            <? endif; ?>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-xs-6">Всего запросов: <strong><?= $numEvents ?></strong></div>
                        <div class="col-xs-6">Суммарное время запросов: <strong><?= round($sumTime * 1000, 2) ?> мс</strong></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <? endif; ?>

    <div class="navbar navbar-fixed-bottom navbar-default">
        <div class="<?= $this->containerClass ?>">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#footer-body">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="footer-body">
                <ul class="nav navbar-nav">
                    <li><a title="Режим исполнения приложения (APPLICATION_ENV)"><span class="glyphicon glyphicon-flash"></span> <?= APPLICATION_ENV ?></a></li>
                    <li><a title="СУБД: хост"><span class="glyphicon glyphicon-cloud"></span> <?= $config->doctrine->host ?></a></li>
                    <li><a title="СУБД: база данных"><span class="fa fa-database"></span> <?= $config->doctrine->schema ?></a></li>
                    <li><a title="СУБД: пользователь"><span class="glyphicon glyphicon-user"></span> <?= $config->doctrine->username ?></a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <? if ($config->debug->configViewer): ?>
                    <li><a title="Показать используемую конфигурацию" href="#" data-toggle="modal" data-target="#DevelConfigViewer">Конфиг</a></li>
                    <? endif; ?>

                    <? if ($config->doctrine->profile): ?>
                    <li><a title="Открыть модельное окно с SQL-профайлером" href="#" data-toggle="modal" data-target="#DevelSqlProfiler">SQL–профайлер (<?= $numEvents ?>)</a></li>
                    <? endif; ?>
                </ul>
            </div>
        </div>
    </div>

</div>
<? endif; ?>
