<?php

/** @var ZFE_View $this */

$config = Zend_Registry::get('config');
?>

<?php if ($config->debug->develToolbar && $this->develToolbar): ?>
    <div id="DevelClearFix"></div>
    <div id="DevelToolbar">
        <?php if ($config->debug->configViewer): ?>
            <div id="DevelConfigViewer" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Конфигурация</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                            <?= $this->configTreeViewer($config->toArray()); ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <?php if ($config->doctrine->profile): ?>
            <div id="DevelSqlProfiler" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-fluid">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">SQL–профайлер</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body table-responsive">
                            <table class="table DevelSqlProfiler-table">
                                <thead>
                                    <tr>
                                        <th>Тип</th>
                                        <th>Время, мс</th>
                                        <th>Запрос</th>
                                        <th>Параметры</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $sumTime = 0; ?>
                                    <?php $numEvents = 0; ?>
                                    <?php foreach (Doctrine_Manager::connection()->getListener() as $key => $event) : /** @var Doctrine_Event $event */ ?>
                                        <?php if (!in_array($event->getName(), ['fetch', 'fetch all', 'prepare'])): ?>
                                            <?php $sumTime += $time = $event->getElapsedSecs(); ?>
                                            <?php if (++$numEvents <= $config->debug->limitShowQueries): ?>
                                                <?php
                                                $params = $event->getParams();
                                                if (!empty($params)) {
                                                    $params = '<pre><ol><li>' . implode('</li><li>', $params) . '</li></ol></pre>';
                                                } else {
                                                    $params = '';
                                                }
                                                ?>
                                                <tr>
                                                    <td><?= $event->getName() ?></td>
                                                    <td><?= round($time * 1000, 2) ?></td>
                                                    <td>
                                                        <div id="DevelSqlListing_<?= $key ?>" class="collapse"><?= $this->formatSql($event->getQuery()) ?></div>
                                                        <a data-bs-toggle="collapse" href="#DevelSqlListing_<?= $key ?>" class="collapsed">
                                                            <span class="sqlHide">скрыть запрос</span>
                                                            <span class="sqlShow">показать запрос</span>
                                                        </a>

                                                        <?php if ($config->doctrine->backtrace): ?>
                                                            <ol id="DevelSqlBacktrace_<?= $key ?>" class="collapse backtrace"><?php
                                                                                                                                foreach ($event->getBacktrace() as $point) {
                                                                                                                                    if (isset($point['file'])) {
                                                                                                                                        echo '<li>' . $point['file'] . '(' . $point['line'] . '): ';
                                                                                                                                        if (isset($point['class'])) {
                                                                                                                                            echo $point['class'] . $point['type'];
                                                                                                                                        }
                                                                                                                                        echo $point['function'] . '(';
                                                                                                                                        if (isset($point['args'])) {
                                                                                                                                            $args = [];
                                                                                                                                            foreach ($point['args'] as $arg) {
                                                                                                                                                if (is_object($arg)) {
                                                                                                                                                    $args[] = get_class($arg);
                                                                                                                                                } else {
                                                                                                                                                    $args[] = var_export($arg);
                                                                                                                                                }
                                                                                                                                            }
                                                                                                                                            echo implode(', ', $args);
                                                                                                                                        }
                                                                                                                                        echo ')</li>';
                                                                                                                                    }
                                                                                                                                } ?></ol>
                                                            <a data-bs-toggle="collapse" href="#DevelSqlBacktrace_<?= $key ?>" class="collapsed">
                                                                <span class="sqlHide">скрыть цепочку вызовов</span>
                                                                <span class="sqlShow">показать цепочку вызовов</span>
                                                            </a>
                                                        <?php endif; ?>
                                                    </td>
                                                    <td><?= $params ?></td>
                                                </tr>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endforeach; ?>

                                    <?php if ($numEvents > $config->debug->limitShowQueries): ?>
                                        <tr>
                                            <td colspan="4" class="text-center empty">Последующие запросы (<?= $numEvents - $config->debug->limitShowQueries ?> шт) скрыты.</td>
                                        </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                        <div class="modal-footer">
                            <div class="row">
                                <div class="col-6">Всего запросов: <strong><?= $numEvents ?></strong></div>
                                <div class="col-6">Суммарное время запросов: <strong><?= round($sumTime * 1000, 2) ?> мс</strong></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <nav class="navbar navbar-expand-sm fixed-bottom navbar-default">
            <div class="<?= $this->containerClass ?>">
                <button type="button" class="navbar-toggler ms-auto" data-bs-toggle="collapse" data-bs-target="#footer-body" aria-controls="footer-body" aria-expanded="false" aria-label="Панель разработчика">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="footer-body">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item"><a class="nav-link" title="Режим исполнения приложения (APPLICATION_ENV)"><span class="glyphicon glyphicon-flash"></span> <?= APPLICATION_ENV ?></a></li>
                        <li class="nav-item"><a class="nav-link" title="СУБД: хост"><span class="glyphicon glyphicon-cloud"></span> <?= $config->doctrine->host ?></a></li>
                        <li class="nav-item"><a class="nav-link" title="СУБД: база данных"><span class="fa fa-database"></span> <?= $config->doctrine->schema ?></a></li>
                        <li class="nav-item"><a class="nav-link" title="СУБД: пользователь"><span class="glyphicon glyphicon-user"></span> <?= $config->doctrine->username ?></a></li>
                    </ul>
                    <ul class="navbar-nav">
                        <?php if ($config->debug->configViewer): ?>
                            <li class="nav-item"><a class="nav-link" title="Показать используемую конфигурацию" href="#" data-bs-toggle="modal" data-bs-target="#DevelConfigViewer">Конфиг</a></li>
                        <?php endif; ?>

                        <?php if ($config->doctrine->profile): ?>
                            <li class="nav-item"><a class="nav-link" title="Открыть модельное окно с SQL-профайлером" href="#" data-bs-toggle="modal" data-bs-target="#DevelSqlProfiler">SQL–профайлер (<?= $numEvents ?>)</a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>

    </div>
<?php endif; ?>