<?php

/** @var ZFE_View $this */
/** @var Zend_Config $config */
$config = Zend_Registry::get('config');
$user = Zend_Registry::get('user');
?>

<nav class="navbar navbar-expand-sm fixed-top navbar-default" role="navigation">
    <div class="<?= $this->containerClass ?>">
        <a class="navbar-brand" href="/" title="<?= is_string($config->brand) ? $config->brand : $config->brand->full ?>">
            <span class="brand-logo"></span>
            <span class="brand-title"><?= is_string($config->brand) ? $config->brand : $config->brand->short ?></span>
        </a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Меню">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="main-menu" class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto">
                <?= $this->menuItems($config->menu) ?>
            </ul>
            <ul class="navbar-nav navbar-nav-end">
                <?php if ($user->role !== 'guest'): ?>
                    <?php
                    if ($config->menuRight) {
                        echo $this->menuItems($config->menuRight);
                    }
                    ?><li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                            <i class="glyphicon glyphicon-user"></i>
                            <span class="navbar-user-name"><?= $user->displayName ?></span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <?php
                            if ($config->menuUser) {
                                echo $this->menuItems($config->menuUser, true, false, true, true);
                            }

                            if ($user->canSwitchRoles) {
                                $items = [];

                                if ($config->menuUser) {
                                    $items['rolesHeader']['divider'] = 1;
                                }

                                $items['rolesHeader']['itemsHeader'] = 'Сменить роль';

                                foreach (Editors::getDictionary('role') as $name => $label) {
                                    $items[$name]['label'] = $label;
                                    $items[$name]['uri'] = '/auth/set-role/role/' . $name;

                                    if ($user->role === $name) {
                                        $items[$name]['active'] = true;
                                    }
                                }

                                $items['rolesAfterDivider']['divider'] = '';

                                echo $this->menuItems($items, false, true, true, true);
                            }
                            ?><li><a class="dropdown-item" href="/auth/logout">Выход</a></li>
                        </ul>
                    </li>
                <?php else: ?>
                    <li class="nav-item">
                        <a class="nav-link" href="/auth/login">Войти</a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</nav>
