<?php
/** @var ZFE_View $this */
?>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <?= $this->headTitle() ?>
    <?= $this->headMeta()
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ?>
    <?= $this->headLink()  // ВНИМАНИЕ! Обратный порядок!
        ->prependStylesheet($this->webpack('main.css'));
    ?>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="/js/html5shiv.min.js"></script>
    <script src="/js/respond.min.js"></script>
    <![endif]-->
</head>
<body data-version="<?= $this->version ?>" class="controller-<?= $this->controllerName ?> action-<?= $this->actionName ?>">
    <?= $this->render('header.phtml') ?>
    <div class="<?= $this->containerClass ?>">
        <?= $this->alerts() ?>
        <?= $this->layout()->content ?>
    </div>
    <?= $this->headScript()  // ВНИМАНИЕ! Обратный порядок!
        ->prependFile($this->webpack('main.js'));
    ?>
    <?/*= $this->notices() */ ?>
    <?= $this->inlineScript() ?>
    <?= $this->render('develtoolbar.phtml') ?>
</body>
</html>
