<?php

/** @var ZFE_View $this */

$config = Zend_Registry::get('config');

// @todo нужно переделать склонение по нормальному
$actionLabel = [
    History::ACTION_TYPE_INSERT => [
        AbstractRecord::GENDER_MASCULINE => 'добавлен',
        AbstractRecord::GENDER_FEMININE => 'добавлена',
        AbstractRecord::GENDER_NEUTER => 'добавлено',
    ],
    History::ACTION_TYPE_UPDATE => [
        AbstractRecord::GENDER_MASCULINE => 'отредактирован',
        AbstractRecord::GENDER_FEMININE => 'отредактирована',
        AbstractRecord::GENDER_NEUTER => 'отредактировано',
    ],
    History::ACTION_TYPE_LINK => [
        AbstractRecord::GENDER_MASCULINE => 'привязан',
        AbstractRecord::GENDER_FEMININE => 'привязана',
        AbstractRecord::GENDER_NEUTER => 'привязано',
    ],
    History::ACTION_TYPE_DELETE => [
        AbstractRecord::GENDER_MASCULINE => 'удален',
        AbstractRecord::GENDER_FEMININE => 'удалена',
        AbstractRecord::GENDER_NEUTER => 'удалено',
    ],
    History::ACTION_TYPE_UNLINK => [
        AbstractRecord::GENDER_MASCULINE => 'отвязан',
        AbstractRecord::GENDER_FEMININE => 'отвязана',
        AbstractRecord::GENDER_NEUTER => 'отвязано',
    ],
    History::ACTION_TYPE_UNDELETE => [
        AbstractRecord::GENDER_MASCULINE => 'восстановлен',
        AbstractRecord::GENDER_FEMININE => 'восстановлена',
        AbstractRecord::GENDER_NEUTER => 'восстановлено',
    ],
    History::ACTION_TYPE_RESTORE => [
        AbstractRecord::GENDER_MASCULINE => 'откатан к предыдущей версии',
        AbstractRecord::GENDER_FEMININE => 'откатана к предыдущей версии',
        AbstractRecord::GENDER_NEUTER => 'откатано к предыдущей версии',
    ],
    History::ACTION_TYPE_MERGE => [
        AbstractRecord::GENDER_MASCULINE => 'объединен',
        AbstractRecord::GENDER_FEMININE => 'объединена',
        AbstractRecord::GENDER_NEUTER => 'объединено',
    ],
];
?>

<h2><?= is_string($config->brand) ? $config->brand : $config->brand->full ?></h2>

<div class="row">
    <div class="col-md-6">
        <h3>Ваши последние изменения</h3>
        <?php if (count($this->myHistory)): ?>
            <dl><?php
                foreach ($this->myHistory as $event) {
                    /** @var History $event */
                    $modelName = AbstractRecord::getModelNameByTableName($event->table_name);
                    if (class_exists($modelName)) {
                        $item = $modelName::hardFind($event->content_id);

                        echo '<dt>';
                        echo $this->DateTime($event->datetime_action);
                        echo ' ' . $actionLabel[$event->action_type][$modelName::$gender] . ' ';
                        echo mb_strtolower($modelName::$nameSingular);
                        echo ':</dt>';

                        if (empty($item)) {
                            echo '<dd class="empty">Запись не найдена.</dd>';
                        } elseif ($item->contains('deleted') && $item->deleted) {
                            echo '<dd>' . $item->getTitle() . '</dd>';
                        } else {
                ?><dd>
                                <a href="<?= $item->getEditUrl() ?>">
                                    <i class="glyphicon glyphicon-edit"></i>
                                    <?= $item ?>
                                </a>
                            </dd><?php
                                }
                            } else {
                                echo '<dt>';
                                echo $this->DateTime($event->datetime_action);
                                echo ' ' . $actionLabel[$event->action_type][AbstractRecord::GENDER_MASCULINE] . ' неизвестный объект</dt>';
                                echo '<dd>Класс объекта: «' . $modelName . '»</dd>';
                            }
                        }
                                    ?></dl>
        <?php else: ?>
            <p class="empty">За последний месяц вы ничего не изменяли и не добавляли.</p>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <h3>Последние изменения после ваших</h3>
        <?php if (count($this->otherHistory)): ?>
            <dl><?php
                foreach ($this->otherHistory as $event) {
                    /** @var History $event */
                    $modelName = AbstractRecord::getModelNameByTableName($event->table_name);
                    if (class_exists($modelName)) {
                        $item = $modelName::hardFind($event->content_id);

                        echo '<dt>';
                        echo $this->DateTime($event->datetime_action);
                        echo ' ' . $actionLabel[$event->action_type][$modelName::$gender] . ' ';
                        echo mb_strtolower($modelName::$nameSingular);
                        echo ' (' . $event->Editors->getShortName() . ')';
                        echo ':</dt>';

                        if (empty($item)) {
                            echo '<dd class="empty">Запись не найдена.</dd>';
                        } elseif ($item->contains('deleted') && $item->deleted) {
                            echo '<dd>' . $item->getTitle() . '</dd>';
                        } else {
                ?><dd>
                                <a href="<?= $item->getEditUrl() ?>">
                                    <i class="glyphicon glyphicon-edit"></i>
                                    <?= $item ?>
                                </a>
                            </dd><?php
                                }
                            } else {
                                echo '<dt>';
                                echo $this->DateTime($event->datetime_action);
                                echo ' ' . $actionLabel[$event->action_type][AbstractRecord::GENDER_MASCULINE] . ' неизвестный объект</dt>';
                                echo '<dd>Класс объекта: «' . $modelName . '»</dd>';
                            }
                        }
                                    ?></dl>
        <?php else: ?>
            <p class="empty">За последний месяц после вас ничего не изменяли и не добавляли.</p>
        <?php endif; ?>
    </div>
</div>