<?php

/** @var Exception */
$e = $this->exception;

if ($this->externalExceptionHandler) {
    throw $e;
}

?>

<div class="alert alert-danger">
    <?php if ($this->displayExceptionMessage): ?>
        <div><?= $this->escape($this->message) ?></div>
        <h4 style="margin: 4px 0 0;"><?= $this->escape($e->getMessage()) ?></h4>
        <?php if ($this->displayException): ?>
            <br />
            <p><?= $this->escape($e->getFile()) ?>(<?= $e->getLine() ?>)</p>
        <?php endif; ?>
    <?php else: ?>
        <h4 style="margin: 0;"><?= $this->escape($this->message) ?></h4>
    <?php endif; ?>
</div>

<?php if ($this->displayException): ?>
    <h3>Стек вызовов</h3>
    <pre><?= $e->getTraceAsString() ?></pre>

    <h3>Параметры запроса</h3>
    <pre><?= $this->escape(var_export($this->request->getParams(), true)) ?></pre>
<?php endif; ?>