<?php

/** @var ZFE_View $this */

$modelName = $this->modelName;
$serviceFields = $modelName::getServiceFields();
$hiddenColumns = $modelName::getHistoryHiddenFields();
$sideHash = $this->hopsHistory()->getSideHash('?');

$versions = [];
foreach ($this->milestones as $version) {
    $versions[$version['version']] =
        'Версия № ' . $version['version'] . ': ' .
        History::$actionTypes[$version['action']] .
        ' в ' . $this->DateTime($version['datetime']);
}
?>

<div class="info">
    <div class="title">Сведения об актуальной версии</div>
    <?= $this->historyMeta($this->curItem) ?>
</div>
<form id="diff" method="post" action="/<?= $this->controllerName ?>/<?= $this->actionName . $sideHash ?>" class="table-responsive">
    <?php if ($this->resource): ?>
        <input type="hidden" name="resource" value="<?= $this->resource ?>" />
    <?php endif; ?>
    <input type="hidden" name="id" value="<?= $this->curItem->id ?>" />
    <table class="table table-hover">
        <thead>
            <tr>
                <th colspan="2" class="diff-left">
                    <?= $this->formSelect('left', $this->leftVersion, ['class' => 'form-control'], $versions) ?>
                    <div>
                        <?php if (empty($this->leftEditor)): ?>
                            Редактор не известен
                        <?php else: ?>
                            Редактор: <?= $this->leftEditor->getNameWithContactInfo() ?>
                        <?php endif; ?>
                    </div>
                </th>
                <th colspan="2" class="diff-right">
                    <?= $this->formSelect('right', $this->rightVersion, ['class' => 'form-control'], $versions) ?>
                    <div>
                        <?php if (empty($this->rightEditor)): ?>
                            Редактор не известен
                        <?php else: ?>
                            Редактор: <?= $this->rightEditor->getNameWithContactInfo() ?>
                        <?php endif; ?>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->curItem->getData() as $column => $value): ?>
                <?php
                // Служебные поля пропускаем
                if (in_array($column, $serviceFields, true)) {
                    continue;
                }

                $leftValue = $this->leftItem->{$column};
                $rightValue = $this->rightItem->{$column};
                ?>
                <tr<?= $leftValue !== $rightValue ? ' class="danger"' : '' ?>>
                    <th class="diff-left"><?= $modelName::getFieldName($column) ?></th>
                    <?php if (in_array($column, $hiddenColumns, true)): ?>
                        <td colspan="2" class="text-center"><em class="empty">значение скрыто</em></td>
                    <?php else: ?>
                        <td class="diff-left"><?= $this->autoFormat($leftValue, $column, $modelName) ?></td>
                        <td class="diff-right"><?= $this->autoFormat($rightValue, $column, $modelName) ?></td>
                    <?php endif; ?>
                    <th class="diff-right"><?= $modelName::getFieldName($column) ?></th>
                    </tr>
                <?php endforeach; ?>
        </tbody>
        <?php if (!$this->readonly): ?>
            <tfoot>
                <tr>
                    <td colspan="2" class="text-center">
                        <?php if ($this->leftVersion !== $this->curItem->version): ?>
                            <a href="<?= $this->curItem->getRestoreToVersion($this->leftVersion) . $sideHash ?>" class="btn btn-danger" data-confirm="Вы уверены, что хотите откатиться к версии <?= $this->leftVersion ?>?">
                                Откатить к версии <?= $this->leftVersion ?>
                            </a>
                        <?php endif; ?>
                    </td>
                    <td colspan="2" class="text-center">
                        <?php if ($this->rightVersion !== $this->curItem->version): ?>
                            <a href="<?= $this->curItem->getRestoreToVersion($this->rightVersion) . $sideHash ?>" class="btn btn-danger" data-confirm="Вы уверены, что хотите откатиться к версии <?= $this->rightVersion ?>?">
                                Откатить к версии <?= $this->rightVersion ?>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            </tfoot>
        <?php endif; ?>
    </table>
</form>