<?php

/** @var ZFE_View $this */

$modelName = $this->modelName;
$tableInstance = Doctrine_Core::getTable($modelName);
$hasEdited = $tableInstance->hasColumn('datetime_edited');
?>

<h4 class="float-start">
    Всего групп дубликатов:
    <?= $modelName::getCountDuplicates() ?>
</h4>

<?php if (count($this->groups)): ?>
    <?= $this->paginator(['containerPrefix' => '<ul class="float-end pagination" style="margin-top:0">']) ?>
    <div class="clearfix"></div>

    <form>
        <?php foreach ($this->groups as $gid => $group): /** @var Doctrine_Collection<ZFE_Model_AbstractRecord> $group */ ?>
            <fieldset class="card">
                <div class="card-header">
                    <h3 class="card-title"><?= $group->getFirst() ?></h3>
                </div>
                <div class="panel-wrap">
                    <div class="loader-mock"></div>
                    <table class="table table-hover" style="width: fit-content;">
                        <thead>
                            <tr>
                                <th><input type="checkbox"
                                        data-action="check-all"
                                        data-target="input[data-group='<?= $gid ?>']"
                                        checked></th>
                                <th></th>
                                <th style="width: 100%;"><?= $modelName::getFieldName('title') ?></th>
                                <th class="text-end"><abbr title="Число ссылок на <?= $this->itemName ?>">Вес</abbr></th>
                                <?php if ($hasEdited): ?>
                                    <th class="text-nowrap">Последняя правка</th>
                                <?php endif; ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($group as $item): ?>
                                <tr data-item-id="<?= $item->id ?>">
                                    <th><input type="checkbox" checked data-group="<?= $gid ?>"></th>
                                    <td class="item-details">
                                        <span class="glyphicon glyphicon-info-sign item-details-icon"
                                            data-bs-title="<?= $this->escape($item->getTitle()) ?>"
                                            data-bs-trigger="hover"
                                            data-bs-html="true"></span>
                                        <div class="item-details-body">
                                            <?= $this->abstractPartial('_view.phtml', [
                                                'modelName' => $modelName,
                                                'item' => $item,
                                            ]) ?>
                                        </div>
                                    </td>
                                    <td>
                                        <a href="<?= $item->getUrl() ?>" target="_blank">
                                            <?= $item ?>
                                        </a>
                                    </td>
                                    <td class="text-end"><?= $item->weight ?></td>
                                    <?= $hasEdited ? $this->lastEditedCell($item, 'text-nowrap') : '' ?>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <input class="btn btn-default btn-sm btn-merge"
                        data-url="<?= $modelName::getMergeHelperUrl() ?>"
                        data-group="<?= $gid ?>"
                        type="button"
                        value="Объединить">

                    <span class="alert alert-info message-loading">Выполняется объединение…</span>
                    <span class="alert alert-error message-error d-none">Ошибка!</span>
                </div>
            </fieldset>
        <?php endforeach; ?>
    </form>

    <?= $this->paginator() ?>
<?php endif; ?>

<script class="zfe-duplications-alert" type="text/x-jquery-tmpl">
    <div class="alert alert-${type} alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <strong>${title}</strong>
        ${message}
    </div>
</script>