<?php

/** @var ZFE_View $this */

$tableInstance = Doctrine_Core::getTable($this->modelName);
$hasStatus = $tableInstance->hasColumn('status');
$editedField = $tableInstance->hasColumn('datetime_edited') ? 'datetime_edited' : null;;
if (!$editedField && $tableInstance->hasColumn('updated_at')) {
    $editedField = 'updated_at';
}
$downHash = $this->hopsHistory()->getDownHash('К результатам поиска', '?', ['totalResults' => ZFE_Paginator::getInstance()->getNumResults()]);
?>

<?php if (count($this->items)): ?>
    <?= $this->paginator() ?>
    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-hover table-sticky-header">
            <thead>
                <tr>
                    <?= $this->sortableHeadCell('id') ?>
                    <?= $this->sortableHeadCell('title') ?>
                    <?= $hasStatus ? $this->sortableHeadCell('status') : '' ?>
                    <?= $editedField ? $this->sortableHeadCell($editedField, 'Последнее изменение') : '' ?>
                    <th class="text-right">Действия</th>
                </tr>
            </thead>
            <tbody>
                <?php $rowIndex = 0;
                foreach ($this->items as $item): ++$rowIndex;
                    /** @var ZFE_Model_AbstractRecord $item */ ?>
                    <tr>
                        <td><?= $item->id ?></td>
                        <td>
                            <a href="<?= $item->getUrl() . $downHash . $this->searchPages()->getHash($rowIndex, '&') ?>">
                                <?= $item->getTitle() ?>
                            </a>
                        </td>
                        <?php if ($hasStatus): ?>
                            <td><?= $item->getStatus() ?></td>
                        <?php endif; ?>
                        <?= $editedField ? $this->lastEditedCell($item) : '' ?>
                        <td class="text-right">

                            <?php if ($this->canDelete && !$item->isDeleted()): ?>
                                <a data-confirm="Вы уверены, что хотите удалить <?= $item::$nameSingular ?> «<?= $this->escape($item->getTitle()) ?>»?"
                                    href="<?= $item->getDeleteUrl() . $downHash ?>"
                                    class="btn btn-link btn-xs">
                                    <i class="glyphicon glyphicon-remove"></i>
                                    Удалить
                                </a>
                            <?php endif; ?>

                            <?php if ($this->canRestore && $item->isDeleted()): ?>
                                <a href="<?= $item->getUndeleteUrl() . $downHash ?>" class="btn btn-link btn-xs">
                                    <i class="glyphicon glyphicon-repeat"></i>
                                    Восстановить
                                </a>
                            <?php endif; ?>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?= $this->paginator() ?>
<?php else: ?>
    <p class="empty" style="clear: both;"><?= $this->listName ?> не найдены.</p>
<?php endif; ?>