<?
    $item = $this->item = $this->curItem;

    $this->controlTabs[] = [
        'action' => 'diff',
        'title' => 'Сравнение версий',
        'class' => 'pull-right',
    ];
?>

<?= $this->abstractRender('_header.phtml') ?>

<? if (file_exists(APPLICATION_PATH . '/views/scripts/' . $this->resource . '/_diff.phtml')): ?>
    <?= $this->render($this->resource . '/_diff.phtml') ?>
<? else: ?>
    <?= $this->render('_abstract/_diff.phtml') ?>
<? endif; ?>
