<?php

/** @var ZFE_View $this */ ?>

<?php if ($this->item->exists()): ?>
    <div class="float-end" style="margin-bottom: 10px;">
        <a href="<?= $this->item->getEditUrl() ?>" target="_blank">
            <span class="glyphicon glyphicon-share-alt"></span>
        </a>
    </div>
<?php endif; ?>

<div class="clearfix"></div>
<?= $this->alerts(); ?>
<?= $this->abstractRender('_edit_form.phtml') ?>