<?php

/** @var ZFE_View $this */ ?>

<div>
    <?= $this->hopsHistory()->getUpBtn() ?>
</div>

<h2>
    <?= $this->listName ?>
    <small>(поиск и объединение дубликатов)</small>
</h2>

<?php if (count($this->groups)): ?>
    <div class="zfe-duplications"><?= $this->abstractRender('_duplicates_list.phtml') ?></div>
<?php else: ?>
    <div class="alert alert-info" role="alert">Дубликаты не найдены.</div>
<?php endif; ?>