<?php
/** @var ZFE_View $this */
?>

<div>
    <?= $this->hopsHistory()->getUpBtn() ?>
</div>

<h2>
    <?= $this->listName ?>
    <small>(поиск и объединение дубликатов)</small>
</h2>

<? if (count($this->groups)): ?>
    <div class="zfe-dublications"><?= $this->abstractRender('_duplicates_list.phtml') ?></div>
<? else: ?>
    <div class="alert alert-info" role="alert">Дубликаты не найдены.</div>
<? endif; ?>
