<?php
$agents = $this->agents;
?>

<? if ($agents && count($agents)) { ?>
<ul class="list-group files-list">
    <? foreach ($agents as $agent) { /** @var ZFE_File_Agent $agent */ ?>
        <? if ($agent->canDownload()) { ?>
            <li class="list-group-item file-list-item">
                <a href="<?= $agent->getDownloadUrl() ?>">
                    <i class="<?= $agent->getIconClass() ?>"></i>
                    <?= $agent->getName() ?>
                    (<?= $agent->getSize() ?>)</a>
                <? } else { ?>
                    <p>
                        <i class="<?= $agent->getIconClass() ?>"></i>
                        <?= $agent->getName() ?>
                        (<?= $agent->getSize() ?>)&nbsp;
                    </p>
            <? } ?>
        </li>
    <? } ?>
</ul>
<? } ?>